[versions]
agp = "8.5.0"
kotlin = "1.9.24"
composeBom = "2024.06.00"
room = "2.6.1"
lifecycle = "2.8.3"
coroutines = "1.8.1"
navigationCompose = "2.7.7"
gson = "2.10.1"
activityCompose = "1.9.0"
coreKtx = "1.13.1"

[libraries]
compose-bom                 = { group = "androidx.compose",          name = "compose-bom",                    version.ref = "composeBom" }
compose-ui                  = { group = "androidx.compose.ui",       name = "ui" }
compose-ui-graphics         = { group = "androidx.compose.ui",       name = "ui-graphics" }
compose-ui-tooling-preview  = { group = "androidx.compose.ui",       name = "ui-tooling-preview" }
compose-ui-tooling          = { group = "androidx.compose.ui",       name = "ui-tooling" }
compose-material3           = { group = "androidx.compose.material3", name = "material3" }
compose-icons-extended      = { group = "androidx.compose.material", name = "material-icons-extended" }
activity-compose            = { group = "androidx.activity",          name = "activity-compose",               version.ref = "activityCompose" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle",         name = "lifecycle-viewmodel-compose",    version.ref = "lifecycle" }
lifecycle-runtime-ktx       = { group = "androidx.lifecycle",         name = "lifecycle-runtime-ktx",          version.ref = "lifecycle" }
navigation-compose          = { group = "androidx.navigation",        name = "navigation-compose",             version.ref = "navigationCompose" }
room-runtime                = { group = "androidx.room",              name = "room-runtime",                   version.ref = "room" }
room-ktx                    = { group = "androidx.room",              name = "room-ktx",                       version.ref = "room" }
room-compiler               = { group = "androidx.room",              name = "room-compiler",                  version.ref = "room" }
coroutines-android          = { group = "org.jetbrains.kotlinx",      name = "kotlinx-coroutines-android",     version.ref = "coroutines" }
gson                        = { group = "com.google.code.gson",       name = "gson",                           version.ref = "gson" }
core-ktx                    = { group = "androidx.core",              name = "core-ktx",                       version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt         = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
